name = "LIKWID"
uuid = "bf22376a-e803-4184-b2ed-56326e3bff83"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.1"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"
