steps:
  - label: "Julia v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      # - JuliaCI/julia-test#v1: ~
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
    env:
      LD_LIBRARY_PATH: "/usr/local/lib"
    command: |
      echo "---- Installing LIKWID"
      wget http://ftp.fau.de/pub/likwid/likwid-stable.tar.gz
      mkdir likwid
      tar -xaf likwid-stable.tar.gz -C likwid --strip-components=1
      cd likwid
      make
      make install
      /usr/sbin/modprobe msr
      /usr/local/bin/likwid-topology -c -C -g
      /usr/local/bin/likwid-perfctr -i
      /usr/local/bin/likwid-perfctr -a
      cd ..
      echo "---- Starting Julia"
      julia --project -e '
        println("--- :julia: Instantiating project")
        using Pkg
        Pkg.instantiate()
        println("--- :julia: Running tests")
        Pkg.test()'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
