steps:
  - label: "Julia v1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      # - JuliaCI/julia-test#v1: ~
      # - JuliaCI/julia-coverage#v1:
          # codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    command: |
      echo "---- Installing LIKWID"
      wget http://ftp.fau.de/pub/likwid/likwid-stable.tar.gz
      mkdir likwid
      tar -xaf likwid-stable.tar.gz -C likwid --strip-components=1
      cd likwid
      make
      make install
      /usr/local/bin/likwid-topology -c -C -g
      modprobe msr
      /usr/local/bin/likwid-perfctr -i
      /usr/local/bin/likwid-perfctr -a
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
